### PR TITLE
fix issue-183

### PR DESCRIPTION
**Pull request by YifengMao**
#183 

i don't know why it can fix the ssh issue, just like they didn't
https://stackoverflow.com/questions/44250224/how-to-debug-a-non-working-passwordless-rsa-certificate-in-openssh-on-alpine

anyway it allows ssh access, and now orca can work with the latest version of eventgen

### CODE REVIEW

**Comment by arctan5x** [comment]
Seems like the branch is out of date with the base branch. Would you please check this before merging?

**Comment by arctan5x** [comment]
@YifengMao Hi Yifeng, did you examine that orca create --egx works after this fix? I am trying the command with Orca 0.8.17 and it is unable to ssh access the container.

**Comment by YifengMao** [comment]
> @YifengMao Hi Yifeng, did you examine that orca create --egx works after this fix? I am trying the command with Orca 0.8.17 and it is unable to ssh access the container.

I just tested:
build image -> run a docker container -> use docker exec to modify authorized_keys -> ssh to the container

i didn't try to upload the image and run with orca. Let me try it.

**Comment by YifengMao** [comment]
> @YifengMao Hi Yifeng, did you examine that orca create --egx works after this fix? I am trying the command with Orca 0.8.17 and it is unable to ssh access the container.

tested. I can ssh. can you please try with this image: stg-repo.splunk.com/perf/service/egx:yifeng

**Pull request merged**
