### PR TITLE
enable test coverage in circleci

### PR DESCRIPTION
**Pull request by li-wu**

### CODE REVIEW

**Comment by li-wu** [comment]
Pls hold the review util I make the htmlcov is successfully uploaded.

**Comment by li-wu** [comment]
The pr is ready for review now. You can check the coverage report here: https://480-5445179-gh.circle-artifacts.com/0/home/circleci/project/htmlcov/index.html as an example.

Currently we only have 6% coverage.  
1. We did not enable unittest in the CI since it has lots of failures; 
2. Most functional tests do not have coverage report;

**Comment by arctan5x** [comment]
@li-wu This is amazing. Now we can quantify our test coverage and set proper goals. 

Seems like you are running coverage on all levels of tests. Which level of test is the html report in the CircleCI artifact for? Is there a way to separate coverage for small, medium, and large and store the reports separately?

**Comment by li-wu** [comment]
> @li-wu This is amazing. Now we can quantify our test coverage and set proper goals.
> 
> Seems like you are running coverage on all levels of tests. Which level of test is the html report in the CircleCI artifact for? Is there a way to separate coverage for small, medium, and large and store the reports separately?

The code coverage is an aggregation of small/medium/large test cases.  Since we currently do not have enough coverage for all the test case. Will separate if we do get enough coverage.

**Pull request merged**
